# Generated by Django 5.0 on 2023-12-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produtos_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
