# Generated by Django 5.0 on 2023-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produtos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.CharField(choices=[('G', 'g'), ('XG', 'xg'), ('M', 'm'), ('PP', 'pp'), ('P', 'p'), ('GG', 'gg')], default='', max_length=2),
        ),
    ]
