# Generated by Django 5.0 on 2023-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_produtos_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.CharField(choices=[('P', 'p'), ('M', 'm'), ('PP', 'pp'), ('G', 'g'), ('GG', 'gg'), ('XG', 'xg')], default='', max_length=2),
        ),
    ]
