# Generated by Django 5.0 on 2023-12-29 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_alter_produtos_descricao_alter_produtos_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.CharField(choices=[('M', 'm'), ('P', 'p'), ('GG', 'gg'), ('G', 'g'), ('XG', 'xg'), ('PP', 'pp')], default='', max_length=2),
        ),
    ]
