# Generated by Django 5.0 on 2023-12-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_produtos_data_alter_produtos_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.CharField(choices=[('M', 'm'), ('G', 'g'), ('XG', 'xg'), ('GG', 'gg'), ('PP', 'pp'), ('P', 'p')], default='', max_length=2),
        ),
    ]
